const isMobile = window.innerWidth <= 600;

const NUM_TABS = 5;

// Diamonds
const REFRESH_TIME = 60000;
const BASE_MAX_DIAMONDS = 10;

// Pack Shop
const UNLOCK_PACK_SHOP_COST = 100;
const UNLOCK_ENTRY_COST = 200;
const REFRESH_ENTRY_BASE_COST = 50;
const PACK_LIFETIME = 300000;

// Achievements
const UNLOCK_ACHIEVEMENTS_COST = 100;

// Charm Shop
const UNLOCK_CHARM_SHOP_COST = 200;

// Sportsbook
const UNLOCK_SPORTSBOOK_COST = 400;

// Math Problems
const EASY_DIAMONDS = 5;
const HARD_DIAMONDS = 10;

// Combat
const COMBAT_START_COST = 200;
const CHALLENGE_COST = 100;
const PYRAMID_LEVELS = 10;
const AUTO_LEVEL = 1;
const DIVIDE_LEVEL = 5;
const CRIT_FACTOR = 1.5;

export {
  REFRESH_TIME,
  BASE_MAX_DIAMONDS,
  UNLOCK_ENTRY_COST,
  REFRESH_ENTRY_BASE_COST,
  EASY_DIAMONDS,
  HARD_DIAMONDS,
  PACK_LIFETIME,
  NUM_TABS,
  UNLOCK_PACK_SHOP_COST,
  UNLOCK_ACHIEVEMENTS_COST,
  UNLOCK_CHARM_SHOP_COST,
  UNLOCK_SPORTSBOOK_COST,
  COMBAT_START_COST,
  CHALLENGE_COST,
  PYRAMID_LEVELS,
  AUTO_LEVEL,
  DIVIDE_LEVEL,
  CRIT_FACTOR,
  isMobile,
};
